# Generated by Django 4.1.2 on 2023-05-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_Folder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="account_image",
        ),
    ]
