# Generated by Django 4.2.1 on 2023-05-17 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App_Folder", "0003_remove_account_status_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="App_Folder.account"
            ),
        ),
    ]
